version: "3"

networks:
  csvs_dbserver_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}

services:
  csvs_dbserver:
    image: ${SID}_${DB_NAME}_i
    container_name: ${SID}_${DB_NAME}_c
    build:
      context: ${DB_PATH}
      dockerfile: Dockerfile
    networks:
      csvs_dbserver_net:
        ipv4_address: ${DB_IP}
    hostname: ${DB_HOSTNAME}
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/db_root_password
      MYSQL_DATABASE: "${DB_DATABASE}"
    volumes:
      - db_data:/var/lib/mysql 
      - ./dbserver/sqlconfig:/docker-entrypoint-initdb.d :ro
    security_opt:
      - "no-new-privileges=true"
      # - "seccomp=default.json"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD-SHELL", "healthcheck.sh --su-mysql --connect --innodb_initialized || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  csvs_webserver:
    image: ${SID}_${WEB_NAME}_i
    container_name: ${SID}_${WEB_NAME}_c
    build:
      context: ${WEB_PATH}
      dockerfile: Dockerfile
    ports:
      - "${WEB_SERVER_PORT}:80"
    networks:
      - csvs_dbserver_net
    hostname: ${WEB_HOSTNAME}
    extra_hosts:
      - "${DB_HOSTNAME}:${DB_IP}"
    depends_on:
      - csvs_dbserver
    security_opt:
      - "no-new-privileges=true"
      - "seccomp=default.json"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 100M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    secrets:
      - db_password 
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      
secrets:
  db_password:
    file: dbserver/db_password.txt
  db_root_password:
    file: dbserver/db_root_password.txt

volumes:
  db_data: