apiVersion: v1
data:
  db-password: d3d3Y2xpZW50MjNDcmVkcwo=
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: db-password
  name: db-password
  namespace: default
type: Opaque

---
apiVersion: v1
kind: Secret
metadata:
  name: db-root-password
  namespace: default
type: Opaque
data:
  password: Q29ycmVjdEhvcnNlQmF0dGVyeVN0YXBsZQ== 